apiVersion: v1
kind: Service
metadata:
  name: testmvcapptfx
  namespace: namespace-workflow-1695287475687
spec:
  type: LoadBalancer
  selector:
    app: testmvcapptfx
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000